# Generated by Django 3.2.9 on 2021-11-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_promoter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
