# Generated by Django 3.2.9 on 2021-11-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_blog_marketingfeature_product_testimonial_videoblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='company_name',
            field=models.CharField(default='skdn', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoblog',
            name='image',
            field=models.FileField(upload_to='videoblog/'),
        ),
    ]
