# Generated by Django 3.2.9 on 2021-11-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='company_sie',
            new_name='company_size',
        ),
        migrations.AddField(
            model_name='contact',
            name='job_role',
            field=models.CharField(choices=[('1', 'C-suite'), ('2', 'VP')], default='resr', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='industry',
            field=models.CharField(choices=[('1', 'Agriculture'), ('2', 'Banking & Finance'), ('3', 'Business Services & Software')], max_length=128),
        ),
    ]
